import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { serializePublicPayload, type JsonObject, type JsonValue } from "../../src/renderer/index.js";

export const PROJECT_ROOT = fileURLToPath(new URL("../../../../", import.meta.url));
export const TEMPLATE_ROOT = join(PROJECT_ROOT, "templates/scientific-console");

const HASH_A = `sha256:${"1".repeat(64)}`;
const HASH_B = `sha256:${"2".repeat(64)}`;
const HASH_C = `sha256:${"3".repeat(64)}`;
const FIELD_APPLICABILITY_DECISION_ID = "applicability.fixture.fields";
const SECTION_APPLICABILITY_DECISION_ID = "applicability.fixture.sections";

const DIRECT_BINDING: JsonObject = {
  source_item_id: "src:included",
  source_snapshot_id: "snapshot:2026-08-24",
  snapshot_registry_hash: HASH_B,
  content_hash: HASH_A,
  excerpt_hash: HASH_A,
  chunk_ids: ["chunk:included:10-14"],
  locator: {
    locator_type: "line_range",
    value: "lines 10-14",
    parser_name: "plain-text",
    parser_version: "1",
  },
  parser_identity: {
    parser_name: "plain-text",
    parser_version: "1",
    configuration_hash: HASH_C,
    parser_result_id: "parser-result:included",
  },
  binding_scope: "content_excerpt",
  binding_role: "direct",
};

export function known(value: JsonValue): JsonObject {
  return {
    state: "known",
    value,
    source_bindings: [DIRECT_BINDING],
    derivation_bindings: [],
    missing_reason: null,
    provenance_status: "complete",
  };
}

export function missing(
  state: "unknown" | "not_applicable" | "withheld",
  reason: string,
): JsonObject {
  return {
    state,
    value: null,
    source_bindings: [],
    derivation_bindings: [],
    missing_reason: reason,
    provenance_status: "absent",
    ...(state === "not_applicable" ? { applicability_decision_id: FIELD_APPLICABILITY_DECISION_ID } : {}),
    ...(state === "withheld"
      ? {
          withholding_reason_code: "source_confidentiality",
          disclosure_decision_id: "disclosure:renderer-fixture",
        }
      : {}),
  };
}

const CORE_SECTIONS = [
  "identity_and_scope",
  "module_and_section_coverage",
  "source_universe_and_coverage",
  "research_questions_and_resolution",
  "entities_materials_and_systems",
  "execution_history",
  "methods_parameters_and_deviations",
  "results_failures_and_dispositions",
  "quantitative_derivations",
  "claims_arguments_and_bridges",
  "conflicts_counterevidence_and_uncertainty",
  "artifacts_and_reproducibility",
  "revisions_corrections_and_retractions",
  "disclosure_and_limitations",
  "validation_and_package_status",
] as const;

function sectionCoverage(sectionId: string): JsonObject {
  return {
    section_id: sectionId,
    applicability: "applicable",
    applicability_decision_id: SECTION_APPLICABILITY_DECISION_ID,
    coverage_status: "partial",
    source_universe_ids: ["universe:registered-test-records"],
    represented_object_ids: [],
    omission_or_gap_reasons: known([
      `The ${sectionId} section is represented for renderer testing, but this fixture is not a completeness claim.`,
    ]),
    evidence_bindings: [DIRECT_BINDING],
    last_evaluated_at: known("2026-08-24T00:00:00.000Z"),
  };
}

function parameter(name: string, value: JsonObject, unit: JsonObject, valueRole: string): JsonObject {
  return { name, value, unit, value_role: valueRole };
}

function artifact(
  artifactId: string,
  role: string,
  contentHash: string,
  location: string,
  supersedes: string[] = [],
): JsonObject {
  return {
    artifact_id: artifactId,
    artifact_version: "1",
    artifact_role: role,
    media_type: known(role === "protocol" ? "text/plain" : "text/csv"),
    location: known(location),
    content_hash: known(contentHash),
    byte_size: known(128),
    access_state: "open",
    disclosure_class: "public",
    created_at: known("2026-02-02T01:00:00.000Z"),
    source_item_ids: ["src:included"],
    derivation_ids: [],
    analysis_run_ids: [],
    supersedes_artifact_ids: supersedes,
    extensions: { domain: "wet_lab" },
  };
}

function axis(state: string, rationale: string, evidenceArtifactIds: string[] = []): JsonObject {
  return {
    state,
    rationale,
    evidence_artifact_ids: evidenceArtifactIds,
    source_bindings: [DIRECT_BINDING],
  };
}

/**
 * A schema-valid deterministic renderer fixture with deliberately distinct
 * epistemic and execution states. It is already a public projection; the
 * renderer is not a redactor and must not invent or recover protected values.
 */
export function makePublicReport(): JsonObject {
  const report: JsonObject = {
    report_id: "report:render-semantics",
    project_id: "project:render-semantics",
    report_version: "1",
    schema_version: "1",
    payload_role: "public_projection",
    title: "Renderer semantics fixture",
    language: "en",
    report_mode: "full_archive",
    created_at: "2026-08-24T00:00:00.000Z",
    scope: {
      scope_statement: "Registered records through the fixed test cutoff.",
      started_at: known("2026-01-01T00:00:00.000Z"),
      ended_at: missing("unknown", "The project end date has not been established."),
      cutoff_at: known("2026-08-24T00:00:00.000Z"),
      included_boundaries: ["registered test records"],
      excluded_boundaries: ["unregistered material"],
    },
    cutoff: known("2026-08-24T00:00:00.000Z"),
    applicability_decisions: [
      {
        applicability_decision_id: "applicability.core.always",
        object_version: "1",
        target_kind: "module",
        target_pointer_or_section_id: "core",
        rule_id: "FA004",
        result: "applicable",
        evaluated_context: "The core module is mandatory.",
        evidence_bindings: [DIRECT_BINDING],
        decision_time: "2026-08-24T00:00:00.000Z",
        extensions: {},
      },
      {
        applicability_decision_id: SECTION_APPLICABILITY_DECISION_ID,
        object_version: "1",
        target_kind: "section",
        target_pointer_or_section_id: "*",
        rule_id: "FA003",
        result: "applicable",
        evaluated_context: "Every listed renderer-fixture section is in scope.",
        evidence_bindings: [DIRECT_BINDING],
        decision_time: "2026-08-24T00:00:00.000Z",
        extensions: { fixture_scope: "wildcard section decision" },
      },
      {
        applicability_decision_id: FIELD_APPLICABILITY_DECISION_ID,
        object_version: "1",
        target_kind: "field",
        target_pointer_or_section_id: "/**",
        rule_id: "FA001",
        result: "not_applicable",
        evaluated_context: "Fixture field applicability was explicitly evaluated.",
        evidence_bindings: [DIRECT_BINDING],
        decision_time: "2026-08-24T00:00:00.000Z",
        extensions: { fixture_scope: "wildcard field decision" },
      },
    ],
    module_manifest: [
      {
        module_id: "core",
        protocol_version: "1",
        status: "enabled",
        applicability_decision_id: "applicability.core.always",
        detected_triggers: [],
        section_ids: [...CORE_SECTIONS],
      },
    ],
    section_coverage: CORE_SECTIONS.map(sectionCoverage),
    source_coverage: {
      universe_id: "universe:registered-test-records",
      title: "Renderer fixture registered source inventory",
      scope_statement: "Two registered source items are in the renderer fixture boundary.",
      inclusion_boundary: "The two source items explicitly registered below.",
      exclusion_boundary: "Any source not registered in this fixture.",
      cutoff: known("2026-08-24T00:00:00.000Z"),
      cutoff_event_semantics: known("The source registry was frozen at the renderer fixture cutoff."),
      authority_basis: "declared_inventory",
      authority_evidence: missing("unknown", "No authoritative source-universe registry is available."),
      enumeration_status: "registered_not_proven_exhaustive",
      snapshot_bindings: ["snapshot:2026-08-24"],
      item_ids: ["src:included", "src:inaccessible"],
      snapshots: [
        {
          source_snapshot_id: "snapshot:2026-08-24",
          created_at: known("2026-08-24T00:00:00.000Z"),
          registry_hash: known(HASH_B),
          snapshot_method: known("Deterministic test-fixture construction"),
          source_bindings: [DIRECT_BINDING],
        },
      ],
      items: [
        {
          source_item_id: "src:included",
          universe_id: "universe:registered-test-records",
          source_kind: "file",
          identity: known("renderer-fixture-included-log"),
          title: known("Included laboratory log"),
          location: known("sources/laboratory-log.txt"),
          content_hash: known(HASH_A),
          registered_at: known("2026-08-24T00:00:00.000Z"),
          snapshot_id: "snapshot:2026-08-24",
          revision_or_snapshot: known("revision 1"),
          disclosure_class: "public",
          disposition: "included",
          disposition_reason: missing("not_applicable", "Included sources do not require a non-inclusion reason."),
          content_access: "available",
          canonical_source_item_id: null,
          equivalence_basis: missing("not_applicable", "The source is not a duplicate."),
          mapped_object_ids: ["rq:effect", "work:completed-project", "result:negative", "claim:key"],
          source_bindings: [DIRECT_BINDING],
          extensions: { domain: "wet_lab" },
        },
        {
          source_item_id: "src:inaccessible",
          universe_id: "universe:registered-test-records",
          source_kind: "external_record",
          identity: known("renderer-fixture-restricted-record"),
          title: known("Restricted collaborator record"),
          location: missing("withheld", "The public projection suppresses the restricted locator."),
          content_hash: missing("unknown", "No bytes were available to hash."),
          registered_at: known("2026-08-24T00:00:00.000Z"),
          snapshot_id: "snapshot:2026-08-24",
          revision_or_snapshot: missing("unknown", "The collaborator did not supply a public revision identifier."),
          disclosure_class: "restricted",
          disposition: "inaccessible",
          disposition_reason: known("The record was registered but not supplied."),
          content_access: "inaccessible",
          canonical_source_item_id: null,
          equivalence_basis: missing("not_applicable", "The source is not a duplicate."),
          mapped_object_ids: [],
          source_bindings: [DIRECT_BINDING],
          extensions: { domain: "general" },
        },
      ],
      reconciliation: {
        registered: 2,
        terminally_disposed: 2,
        included: 1,
        excluded_with_reason: 0,
        unreadable: 0,
        inaccessible: 1,
        duplicate: 0,
        unmapped: 0,
        pending: 0,
        included_mapped: 1,
      },
      coverage_axes: {
        inventory_accounting: "complete",
        accessibility: "limitations_present",
        scientific_incorporation: "partial",
      },
      report_completeness: "registered_sources_accounted_for",
      coverage_limitations: ["The registered source list is not an authoritative universe."],
    },
    research_questions: [
      {
        research_question_id: "rq:effect",
        research_question_version: "1",
        question: "Does the registered evidence establish the proposed effect?",
        rationale: known("The question was declared before this reporting pass."),
        resolution_criterion_timing: "predefined",
        resolution_criteria: known("A qualified answer with interpretable controls."),
        resolution_status: "partially_resolved",
        qualified_answer: known("The registered evidence is insufficient for an unqualified effect claim."),
        claim_ids: ["claim:key"],
        limitation_ids: ["lim:coverage"],
        source_bindings: [DIRECT_BINDING],
        extensions: { domain: "wet_lab" },
      },
    ],
    entities: [
      {
        entity_id: "entity:withheld",
        entity_version: "1",
        entity_kind: "sample",
        label: missing("withheld", "The public projection withholds the sample label."),
        identifiers: [],
        identity_status: "withheld",
        source_bindings: [],
        extensions: { domain: "wet_lab" },
      },
    ],
    campaigns: [
      {
        campaign_id: "campaign:fixture",
        campaign_version: "1",
        title: "Fixture campaign",
        objective: known("Preserve planned, completed, failed, and external work distinctly."),
        work_state: "attempted",
        execution_scope: "this_project",
        work_unit_ids: ["work:completed-project", "work:planned", "work:not-performed", "work:external-completed"],
        source_bindings: [DIRECT_BINDING],
        extensions: { domain: "wet_lab" },
      },
    ],
    work_units: [
      {
        work_unit_id: "work:completed-project",
        work_unit_version: "1",
        campaign_id: "campaign:fixture",
        title: "Project assay with failed first attempt",
        objective: known("Measure the registered assay endpoint."),
        work_state: "completed",
        execution_scope: "this_project",
        completion_criterion_timing: "predefined",
        completion_criteria: known("One interpretable successful attempt."),
        completion_assessment: known("The retry succeeded and produced the declared output."),
        completion_evidence: [DIRECT_BINDING],
        attempt_ids: ["attempt:failed", "attempt:retry"],
        method_ids: ["method:assay"],
        decision_event_ids: [],
        input_entity_ids: ["entity:withheld"],
        output_object_ids: ["result:negative", "artifact:result"],
        source_bindings: [DIRECT_BINDING],
        extensions: { domain: "wet_lab" },
      },
      {
        work_unit_id: "work:planned",
        work_unit_version: "1",
        campaign_id: "campaign:fixture",
        title: "Planned follow-up",
        objective: known("Collect an independent follow-up observation."),
        work_state: "planned",
        execution_scope: "this_project",
        completion_criterion_timing: "predefined",
        completion_criteria: known("One independent follow-up attempt."),
        completion_assessment: missing("unknown", "The planned work has not been executed."),
        completion_evidence: [],
        attempt_ids: [],
        method_ids: [],
        decision_event_ids: [],
        input_entity_ids: [],
        output_object_ids: [],
        source_bindings: [DIRECT_BINDING],
        extensions: { domain: "wet_lab" },
      },
      {
        work_unit_id: "work:not-performed",
        work_unit_version: "1",
        campaign_id: "campaign:fixture",
        title: "Cancelled optional analysis",
        objective: known("Assess an optional endpoint."),
        work_state: "not_performed",
        execution_scope: "this_project",
        completion_criterion_timing: "not_applicable",
        completion_criteria: missing("not_applicable", "Completion criteria do not apply to a cancelled unit."),
        completion_assessment: missing("not_applicable", "No completion assessment applies because the work was not performed."),
        completion_evidence: [],
        attempt_ids: [],
        method_ids: [],
        decision_event_ids: [],
        input_entity_ids: [],
        output_object_ids: [],
        source_bindings: [DIRECT_BINDING],
        extensions: { domain: "general" },
      },
      {
        work_unit_id: "work:external-completed",
        work_unit_version: "1",
        campaign_id: "campaign:fixture",
        title: "Collaborator assay reported complete",
        objective: known("Record collaborator-reported context."),
        work_state: "completed",
        execution_scope: "external_study",
        completion_criterion_timing: "predefined",
        completion_criteria: known("Completion as reported by the external study."),
        completion_assessment: known("The external declaration reports its own criterion was met."),
        completion_evidence: [DIRECT_BINDING],
        attempt_ids: ["attempt:external"],
        method_ids: [],
        decision_event_ids: [],
        input_entity_ids: [],
        output_object_ids: [],
        source_bindings: [DIRECT_BINDING],
        extensions: { domain: "wet_lab" },
      },
    ],
    attempts: [
      {
        attempt_id: "attempt:failed",
        attempt_version: "1",
        work_unit_id: "work:completed-project",
        attempt_ordinal: 1,
        execution_scope: "this_project",
        attempt_outcome: "failed",
        started_at: known("2026-02-01T00:00:00.000Z"),
        ended_at: known("2026-02-01T01:00:00.000Z"),
        method_ids: ["method:assay"],
        parameter_set: [],
        input_material_ids: [],
        input_artifact_ids: [],
        segment_ids: ["segment:failed"],
        result_ids: ["result:excluded"],
        failure_event_ids: ["failure:instrument"],
        output_artifact_ids: ["artifact:partial"],
        usable_output_status: "usable_with_qualification",
        superseded_by_attempt_id: "attempt:retry",
        source_bindings: [DIRECT_BINDING],
        extensions: { domain: "wet_lab" },
      },
      {
        attempt_id: "attempt:retry",
        attempt_version: "1",
        work_unit_id: "work:completed-project",
        attempt_ordinal: 2,
        execution_scope: "this_project",
        attempt_outcome: "succeeded",
        started_at: known("2026-02-02T00:00:00.000Z"),
        ended_at: known("2026-02-02T01:00:00.000Z"),
        method_ids: ["method:assay"],
        parameter_set: [],
        input_material_ids: [],
        input_artifact_ids: ["artifact:partial"],
        segment_ids: ["segment:retry"],
        result_ids: ["result:negative"],
        failure_event_ids: [],
        output_artifact_ids: ["artifact:result"],
        usable_output_status: "usable",
        superseded_by_attempt_id: null,
        source_bindings: [DIRECT_BINDING],
        extensions: { domain: "wet_lab" },
      },
      {
        attempt_id: "attempt:external",
        attempt_version: "1",
        work_unit_id: "work:external-completed",
        attempt_ordinal: 1,
        execution_scope: "external_study",
        attempt_outcome: "succeeded",
        started_at: missing("unknown", "The external start time was not supplied."),
        ended_at: missing("unknown", "The external end time was not supplied."),
        method_ids: [],
        parameter_set: [],
        input_material_ids: [],
        input_artifact_ids: [],
        segment_ids: [],
        result_ids: [],
        failure_event_ids: [],
        output_artifact_ids: [],
        usable_output_status: "usable",
        superseded_by_attempt_id: null,
        source_bindings: [DIRECT_BINDING],
        extensions: { domain: "wet_lab" },
      },
    ],
    segments: [
      {
        segment_id: "segment:failed",
        segment_version: "1",
        attempt_id: "attempt:failed",
        segment_ordinal: 1,
        segment_kind: "phase",
        segment_state: "crashed",
        predecessor_segment_id: null,
        restart_reason: missing("not_applicable", "This was not a restart segment."),
        checkpoint_input_artifact_id: null,
        checkpoint_output_artifact_id: "artifact:partial",
        parameter_diff: missing("not_applicable", "This first segment has no predecessor parameter set."),
        started_at: known("2026-02-01T00:00:00.000Z"),
        ended_at: known("2026-02-01T01:00:00.000Z"),
        parameters: [],
        result_ids: ["result:excluded"],
        failure_event_ids: ["failure:instrument"],
        output_artifact_ids: ["artifact:partial"],
        source_bindings: [DIRECT_BINDING],
        extensions: { domain: "wet_lab" },
      },
      {
        segment_id: "segment:retry",
        segment_version: "1",
        attempt_id: "attempt:retry",
        segment_ordinal: 1,
        segment_kind: "restart",
        segment_state: "completed",
        predecessor_segment_id: "segment:failed",
        restart_reason: known("The instrument fault was corrected before retry."),
        checkpoint_input_artifact_id: "artifact:partial",
        checkpoint_output_artifact_id: "artifact:result",
        parameter_diff: known(["Instrument fault corrected; scientific assay parameters unchanged."]),
        started_at: known("2026-02-02T00:00:00.000Z"),
        ended_at: known("2026-02-02T01:00:00.000Z"),
        parameters: [],
        result_ids: ["result:negative"],
        failure_event_ids: [],
        output_artifact_ids: ["artifact:result"],
        source_bindings: [DIRECT_BINDING],
        extensions: { domain: "wet_lab" },
      },
    ],
    methods: [
      {
        method_id: "method:assay",
        method_version: "1",
        name: "Registered assay method",
        method_kind: "assay",
        execution_status: "performed",
        execution_scope: "this_project",
        description: known("The actual and planned parameter records remain separate."),
        planned_parameters: [
          parameter("temperature", known(20), known("degree Celsius"), "planned"),
          parameter("duration", known(45), known("minute"), "planned"),
        ],
        actual_parameters: [
          parameter("temperature", missing("unknown", "Temperature was not recorded."), known("degree Celsius"), "actual"),
          parameter("optional_note", missing("not_applicable", "No optional note applies."), missing("not_applicable", "A note has no unit."), "actual"),
          parameter("sample_label", missing("withheld", "The sample label is restricted."), missing("not_applicable", "A label has no unit."), "actual"),
          parameter("duration", known(60), known("minute"), "actual"),
        ],
        protocol_artifact_ids: ["artifact:protocol"],
        deviation_descriptions: ["The actual duration differed from the plan."],
        source_bindings: [DIRECT_BINDING],
        extensions: { domain: "wet_lab" },
      },
    ],
    decision_events: [
      {
        decision_event_id: "decision:retract-result",
        decision_event_version: "1",
        decision_kind: "other",
        description: "Retract the superseded estimate after the correction.",
        timing_class: "post_hoc",
        decided_at: known("2026-03-01T00:00:00.000Z"),
        decision_maker: known("Fixture reviewer"),
        triggering_object_ids: ["result:retracted"],
        affected_object_ids: ["result:retracted"],
        rationale: known("A registered source correction invalidated the estimate."),
        alternatives_considered: known(["Qualify the earlier estimate without retracting it."]),
        source_bindings: [{ ...DIRECT_BINDING, binding_role: "decision_timing" }],
        extensions: { domain: "wet_lab" },
      },
    ],
    materials: [],
    material_relationships: [],
    analysis_populations: [],
    data_slices: [],
    derivations: [],
    invocations: [],
    environments: [],
    random_states: [],
    analysis_runs: [],
    results: [
      {
        result_id: "result:negative",
        result_version: "1",
        result_kind: "quantitative",
        statement: "No detectable effect was recorded, but control adequacy was insufficient.",
        work_unit_id: "work:completed-project",
        attempt_id: "attempt:retry",
        segment_id: "segment:retry",
        analysis_population_id: null,
        estimand: known("difference in registered endpoint"),
        population_or_system: known("The registered assay system"),
        condition: known("The recorded fixture condition"),
        time_or_frame_scope: known("The completed retry observation interval"),
        unit: known("arbitrary unit"),
        effect_estimate: {
          estimate: known(0),
          unit: known("arbitrary unit"),
          scale: known("linear"),
          interval: {
            lower: known(-2),
            upper: known(2),
            level: known(0.95),
            interval_kind: "confidence",
            unit: known("arbitrary unit"),
          },
          p_value: missing("unknown", "The p-value was not recorded."),
          sample_or_analysis_unit_count: known(4),
          estimation_method: known("Recorded fixture estimate"),
        },
        derivation_closure_status: "partial",
        scientific_effect_class: "no_detectable_effect",
        statistical_decision: "do_not_reject_null",
        interpretability_status: "qualified",
        record_disposition: "primary",
        disposition_reason: missing("not_applicable", "Primary results do not require an exclusion reason."),
        qualification_ids: ["failure:instrument"],
        blocker_ids: ["failure:instrument"],
        negative_evidence_assessment: {
          control_status: "failed",
          quality_control_status: "partial",
          sensitivity_status: "not_established",
          detection_limit: missing("unknown", "The detection limit was not recorded."),
          minimum_detectable_effect: missing("unknown", "The MDE was not recorded."),
          equivalence_bounds: null,
          observed_interval: null,
          eligible_for_biological_counterevidence: false,
          eligibility_reason: "The positive control failed and sensitivity is unknown.",
        },
        data_slice_ids: [],
        derivation_ids: [],
        analysis_run_ids: [],
        output_artifact_ids: ["artifact:result"],
        decision_event_ids: [],
        conflict_set_ids: [],
        source_bindings: [DIRECT_BINDING],
        extensions: { domain: "wet_lab" },
      },
      {
        result_id: "result:excluded",
        result_version: "1",
        result_kind: "qualitative",
        statement: "A contaminated observation was excluded from primary use.",
        work_unit_id: "work:completed-project",
        attempt_id: "attempt:failed",
        segment_id: "segment:failed",
        analysis_population_id: null,
        estimand: missing("not_applicable", "The qualitative record has no estimand."),
        population_or_system: known("The failed first-attempt assay system"),
        condition: known("Instrument fault condition"),
        time_or_frame_scope: known("The first attempt before the fault"),
        unit: missing("not_applicable", "The qualitative record has no unit."),
        effect_estimate: null,
        derivation_closure_status: "absent",
        scientific_effect_class: "not_estimated",
        statistical_decision: "not_performed",
        interpretability_status: "not_interpretable",
        record_disposition: "excluded",
        disposition_reason: known("The instrument fault invalidated primary use."),
        qualification_ids: [],
        blocker_ids: ["failure:instrument"],
        negative_evidence_assessment: null,
        data_slice_ids: [],
        derivation_ids: [],
        analysis_run_ids: [],
        output_artifact_ids: ["artifact:partial"],
        decision_event_ids: ["decision:retract-result"],
        conflict_set_ids: [],
        source_bindings: [DIRECT_BINDING],
        extensions: { domain: "wet_lab" },
      },
      {
        result_id: "result:retracted",
        result_version: "2",
        result_kind: "quantitative",
        statement: "This earlier positive estimate was retracted after correction.",
        work_unit_id: "work:completed-project",
        attempt_id: "attempt:failed",
        segment_id: "segment:failed",
        analysis_population_id: null,
        estimand: known("superseded endpoint estimate"),
        population_or_system: known("The registered assay system"),
        condition: known("The original analysis condition"),
        time_or_frame_scope: known("The original observation interval"),
        unit: known("arbitrary unit"),
        effect_estimate: {
          estimate: known(5),
          unit: known("arbitrary unit"),
          scale: known("linear"),
          interval: null,
          p_value: missing("unknown", "The retracted record does not retain a reliable p-value."),
          sample_or_analysis_unit_count: missing("unknown", "The retracted record does not retain a reliable analysis-unit count."),
          estimation_method: known("Superseded source estimate retained only as a retracted historical record"),
        },
        derivation_closure_status: "partial",
        scientific_effect_class: "increase",
        statistical_decision: "reject_null",
        interpretability_status: "interpretable",
        record_disposition: "retracted",
        disposition_reason: known("A source correction invalidated the estimate."),
        qualification_ids: [],
        blocker_ids: [],
        negative_evidence_assessment: null,
        data_slice_ids: [],
        derivation_ids: [],
        analysis_run_ids: [],
        output_artifact_ids: [],
        decision_event_ids: ["decision:retract-result"],
        conflict_set_ids: [],
        source_bindings: [DIRECT_BINDING],
        extensions: { domain: "wet_lab" },
      },
    ],
    failures: [
      {
        failure_event_id: "failure:instrument",
        failure_event_version: "1",
        failure_class: "instrument",
        severity: "recoverable",
        description: "The first attempt stopped after an instrument fault.",
        onset_or_detection: known("2026-02-01T01:00:00.000Z"),
        affected_object_id: "attempt:failed",
        work_unit_id: "work:completed-project",
        attempt_id: "attempt:failed",
        segment_id: "segment:failed",
        related_object_ids: ["result:excluded"],
        partial_result_ids: ["result:excluded"],
        impact: "The partial output is qualified and cannot replace the successful retry.",
        resolution_status: "resolved_for_future_attempts",
        recovery_attempt_ids: ["attempt:retry"],
        evidence_bindings: [DIRECT_BINDING],
        extensions: { domain: "wet_lab" },
      },
    ],
    evidence_items: [
      {
        evidence_item_id: "evidence:support",
        evidence_item_version: "1",
        evidence_kind: "result",
        summary: "The completed retry supplied a qualified result.",
        result_ids: ["result:negative"],
        artifact_ids: ["artifact:result"],
        data_slice_ids: [],
        derivation_ids: [],
        analysis_run_ids: [],
        source_item_ids: ["src:included"],
        evidence_status: "qualified",
        quality_assessment: "moderate",
        dependency_group_ids: ["dependency:assay"],
        source_bindings: [DIRECT_BINDING],
        extensions: { domain: "wet_lab" },
      },
      {
        evidence_item_id: "evidence:counter",
        evidence_item_version: "1",
        evidence_kind: "counterevidence",
        summary: "The failed positive control limits the negative interpretation.",
        result_ids: ["result:negative"],
        artifact_ids: [],
        data_slice_ids: [],
        derivation_ids: [],
        analysis_run_ids: [],
        source_item_ids: ["src:included"],
        evidence_status: "active",
        quality_assessment: "high",
        dependency_group_ids: ["dependency:assay"],
        source_bindings: [DIRECT_BINDING],
        extensions: { domain: "wet_lab" },
      },
    ],
    evidence_edges: [
      {
        evidence_edge_id: "edge:support",
        evidence_item_id: "evidence:support",
        claim_id: "claim:key",
        relationship: "supports",
        dependency_group_id: "dependency:assay",
        weighting_note: known("Count once within the shared assay dependency group."),
        source_bindings: [DIRECT_BINDING],
      },
      {
        evidence_edge_id: "edge:counter",
        evidence_item_id: "evidence:counter",
        claim_id: "claim:key",
        relationship: "qualifies",
        dependency_group_id: "dependency:assay",
        weighting_note: known("Retain this control failure with the qualified claim."),
        source_bindings: [DIRECT_BINDING],
      },
    ],
    evidence_dependency_groups: [
      {
        dependency_group_id: "dependency:assay",
        dependency_basis: known("Both evidence items arise from the same assay and control set."),
        shared_ancestor_ids: ["attempt:retry"],
        assessment_state: "dependent",
        evidence_item_ids: ["evidence:support", "evidence:counter"],
        source_bindings: [DIRECT_BINDING],
      },
    ],
    claims: [
      {
        claim_id: "claim:key",
        object_version: "1",
        proposition: "The registered evidence supports only a qualified comparison.",
        claim_type: "comparative",
        subject_bindings: [
          { object_type: "research_question", object_id: "rq:effect", object_version: "1" },
        ],
        context: known("Within the registered assay and its failed control."),
        scope: known("Only the registered renderer fixture boundary."),
        decision_timing: "predefined",
        support_status: "qualified",
        evidence_edge_ids: ["edge:support"],
        dependency_edge_ids: [],
        counterevidence_edge_ids: ["edge:counter"],
        argument_step_ids: [],
        cross_domain_bridge_ids: [],
        conflict_set_ids: [],
        limitation_ids: ["lim:coverage"],
        revision_event_ids: [],
        source_bindings: [DIRECT_BINDING],
        extensions: { domain: "wet_lab" },
      },
    ],
    argument_steps: [],
    argument_edges: [],
    claim_dependencies: [],
    cross_domain_bridges: [],
    conflict_sets: [],
    conflict_member_edges: [],
    artifacts: [
      artifact("artifact:partial", "result_output", HASH_A, "artifacts/partial.csv"),
      artifact("artifact:result", "result_output", HASH_B, "artifacts/result.csv", ["artifact:partial"]),
      artifact("artifact:protocol", "protocol", HASH_C, "artifacts/protocol.txt"),
    ],
    reproducibility_units: [
      {
        reproducibility_unit_id: "repro:assay",
        object_version: "1",
        title: "Registered assay documentation unit",
        unit_kind: "wet_lab_experiment",
        criticality: "critical",
        scope: known("The project assay and its linked output."),
        covered_work_unit_ids: ["work:completed-project"],
        covered_analysis_run_ids: [],
        covered_claim_ids: ["claim:key"],
        covered_output_ids: ["artifact:result"],
        historical_invocation_ids: [],
        recipe_id: null,
        input_closure: axis("partial", "One registered source is inaccessible."),
        artifact_closure: axis("satisfied", "The declared output artifact is integrity-bound.", ["artifact:result"]),
        environment_record: { record_id: null, assessment: axis("partial", "Only selected laboratory conditions are recorded.") },
        random_state_record: { record_id: null, assessment: axis("not_applicable", "No computational random state applies.") },
        access_assessment: {
          status: "available_now",
          conditions: missing("not_applicable", "No additional access conditions apply to the bundled record."),
          artifact_ids: ["artifact:result"],
          source_bindings: [DIRECT_BINDING],
        },
        comparison_specification: {
          comparator_id: "comparator:assay",
          timing_classification: "not_applicable",
          comparator_type: "manual_protocol_criteria",
          targets: missing("not_applicable", "No replay comparison is claimed at R0."),
          equivalence_definition: missing("not_applicable", "No replay comparison is claimed at R0."),
          tolerances: missing("not_applicable", "No replay comparison is claimed at R0."),
          allowed_nondeterminism: missing("not_applicable", "No replay comparison is claimed at R0."),
          failure_conditions: missing("not_applicable", "No replay comparison is claimed at R0."),
          source_bindings: [DIRECT_BINDING],
        },
        replay_events: [],
        independent_reproduction_events: [],
        axis_assessments: {
          provenance_closure: axis("partial", "One registered source is inaccessible."),
          recipe_fidelity: axis("unsatisfied", "No replay recipe is declared."),
          data_and_artifact_access: axis("satisfied", "The declared output artifact is available.", ["artifact:result"]),
          environment_capture: axis("partial", "Only selected laboratory conditions are recorded."),
          random_state_capture: axis("not_applicable", "No computational random state applies."),
          replay_verification: axis("unsatisfied", "No verification replay is claimed."),
          independent_computational_reproduction: axis("not_applicable", "Computational reproduction does not apply."),
          independent_experimental_replication: axis("unsatisfied", "No independent experimental replication is recorded."),
          claim_and_output_coverage: axis("partial", "The key claim and output are covered, but source closure is partial.", ["artifact:result"]),
        },
        conservative_level: "R0_documented",
        level_reason: "The scoped target and partial provenance are documented; replay prerequisites are not claimed.",
        limitation_ids: ["lim:coverage"],
        source_bindings: [DIRECT_BINDING],
        extensions: { domain: "wet_lab" },
      },
    ],
    limitations: [
      {
        limitation_id: "lim:coverage",
        category: "source_coverage",
        statement: "The registered source list is not an authoritative source universe.",
        impact: "Global completeness cannot be established.",
        affected_object_ids: ["claim:key"],
        resolution_status: "open",
        source_bindings: [DIRECT_BINDING],
      },
    ],
    revision_events: [
      {
        revision_event_id: "revision:retraction",
        revision_event_version: "1",
        event_kind: "retraction",
        occurred_at: known("2026-03-01T00:00:00.000Z"),
        reason: "A registered correction invalidated the earlier positive estimate.",
        superseded_object_refs: [
          { object_type: "result", object_id: "result:retracted", object_version: "1" },
        ],
        replacement_object_refs: [],
        invalidated_object_ids: ["result:retracted"],
        review_required_object_ids: ["claim:key"],
        impact_statement: "The earlier positive estimate is retracted and downstream use requires review.",
        source_bindings: [DIRECT_BINDING],
        extensions: { domain: "wet_lab" },
      },
    ],
    review_tasks: [
      {
        review_task_id: "review:coverage",
        category: "other",
        description: "Resolve whether additional sources exist outside the registered list.",
        severity: "blocking",
        affected_object_ids: ["claim:key"],
        required_reviewer_role: "source custodian",
        status: "open",
      },
    ],
    disclosure_state: {
      level: "public",
      projection_status: "projected",
      withheld_field_count: 3,
      omitted_object_count: 0,
      projection_id: "projection:render-semantics",
    },
    extensions: {},
  };

  const representedBySection: Record<string, string[]> = {
    research_questions_and_resolution: ["rq:effect"],
    entities_materials_and_systems: ["entity:withheld"],
    execution_history: ["campaign:fixture", "work:completed-project", "attempt:failed", "attempt:retry", "segment:failed", "segment:retry"],
    methods_parameters_and_deviations: ["method:assay"],
    results_failures_and_dispositions: ["result:negative", "result:excluded", "result:retracted", "failure:instrument"],
    claims_arguments_and_bridges: ["claim:key", "evidence:support", "evidence:counter"],
    artifacts_and_reproducibility: ["artifact:result", "repro:assay"],
    revisions_corrections_and_retractions: ["revision:retraction"],
    disclosure_and_limitations: ["lim:coverage"],
  };
  for (const section of report.section_coverage as JsonObject[]) {
    const id = section.section_id;
    if (typeof id === "string") section.represented_object_ids = representedBySection[id] ?? [];
  }
  return report;
}

export function cloneReport(report: JsonObject): JsonObject {
  return JSON.parse(JSON.stringify(report)) as JsonObject;
}

export function makeValidAttestation(
  report: JsonObject,
  scientificPayloadHash: string,
): JsonObject {
  return {
    attestation_id: "attestation:render-semantics",
    attestation_version: "1",
    schema_version: "1",
    report_id: report.report_id as string,
    report_version: report.report_version as string,
    scientific_payload_hash: scientificPayloadHash,
    payload_hash_basis: "canonical-json-v1",
    canonicalization: "sorted-keys-utf8-v1",
    payload_byte_size: new TextEncoder().encode(serializePublicPayload(report)).byteLength,
    schema_set_hash: HASH_A,
    ruleset_id: "ruleset:fixture",
    ruleset_version: "1",
    ruleset_hash: HASH_C,
    severity_profile: "fixture",
    disclosure_projection_binding: {
      projection_id: "projection:render-semantics",
      projection_hash: HASH_B,
      source_payload_hash: HASH_A,
      projected_payload_hash: scientificPayloadHash,
      verification_status: "pass",
    },
    validation_scope: "full",
    coverage: {
      registry_rule_count: 1,
      executed_registry_rule_ids: ["fixture:structural"],
      skipped_registry_rule_ids: [],
      loaded_overlay_ids: [],
      domain_pack_status: "pass",
      profile_prerequisite_status: "pass",
      full_registry_coverage: true,
      full_domain_coverage: true,
      profile_prerequisites_complete: true,
      release_coverage_complete: true,
      compiled_support_manifest_hash: HASH_C,
    },
    started_at: "2026-08-24T01:00:00.000Z",
    completed_at: "2026-08-24T01:00:01.000Z",
    validator: {
      name: "fixture-validator",
      version: "1",
      build_hash: HASH_B,
    },
    checks: [
      {
        check_id: "fixture:structural",
        category: "schema_and_missingness",
        rule_code: "fixture:structural",
        status: "pass",
        severity: "blocking",
        message: "The deterministic renderer fixture passed its structural check.",
        instance_pointer: "",
        affected_object_ids: [],
        waiver: null,
        evidence_artifact_ids: [],
      },
    ],
    unresolved_blocking_check_ids: [],
    summary: {
      total: 1,
      passed: 1,
      failed: 0,
      not_run: 0,
      errors: 0,
      not_applicable: 0,
      warnings: 0,
      blocking_findings: 0,
      waived_findings: 0,
    },
    overall_status: "valid",
    signature: null,
    extensions: {},
  };
}

export function makeGenerationAudit(
  report: JsonObject,
  scientificPayloadHash: string,
): JsonObject {
  return {
    generation_audit_id: "generation-audit:render-semantics",
    audit_version: "1",
    schema_version: "1",
    report_id: report.report_id as string,
    report_version: report.report_version as string,
    scientific_payload_hash: scientificPayloadHash,
    audit_disclosure_level: "public",
    scientific_payload_impact: "none",
    removable_without_scientific_change: true,
    stage: "candidate_patch_construction",
    generation_invocations: [
      {
        invocation_id: "generation-invocation:1",
        stage: "candidate_patch_construction",
      },
    ],
    audit_events: [
      {
        event_id: "generation-event:1",
        event_kind: "candidate_reviewed",
        actor_kind: "automated_assistance",
        description: "A candidate patch was prepared for human review.",
      },
      {
        event_id: "generation-event:2",
        event_kind: "human_decision_recorded",
        actor_kind: "human",
        description: "A reviewer recorded a decision outside the scientific payload.",
      },
    ],
  };
}

export function allIdentifierValues(value: JsonValue): string[] {
  const identifiers = new Set<string>();
  const visit = (current: JsonValue, key: string | null): void => {
    if (typeof current === "string") {
      if (key !== null && (key === "report_id" || key.endsWith("_id"))) {
        identifiers.add(current);
      }
      return;
    }
    if (Array.isArray(current)) {
      current.forEach((item) => visit(item, key));
      return;
    }
    if (current === null || typeof current !== "object") return;
    Object.entries(current).forEach(([childKey, child]) => {
      if (childKey.endsWith("_ids") && Array.isArray(child)) {
        child.forEach((item) => {
          if (typeof item === "string") identifiers.add(item);
        });
      } else {
        visit(child, childKey);
      }
    });
  };
  visit(value, null);
  return [...identifiers].sort((left, right) => left.localeCompare(right, "en"));
}
