import path from "node:path";
import { lstat, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";

import { renderReport } from "../renderer/index.js";
import type { PackageFile } from "./types.js";
import { sha256File } from "./hash.js";

export const TRUSTED_RENDERER_OUTPUT_PATHS = new Set([
  "annex/index.html",
  "annex/records.html",
  "assets/icons.svg",
  "assets/print.css",
  "assets/report.css",
  "assets/report.js",
  "report.html",
  "scientific-report.public.json",
  "validation-attestation.json",
  "audit/generation-audit.json",
]);

const TRUSTED_HTML_OUTPUT_PATHS = [
  "annex/index.html",
  "annex/records.html",
  "report.html",
] as const;

export interface TrustedRenderIssue {
  code: "TRUSTED_RENDER_OUTPUT_MISSING" | "TRUSTED_RENDER_OUTPUT_MISMATCH" | "UNTRUSTED_GENERATED_OUTPUT";
  path: string;
  message: string;
  expectedHash?: string;
  actualHash?: string;
}

export function isWorkingCopyExtensions(extensions: Readonly<Record<string, unknown>>): boolean {
  return extensions.artifact_mode === "working_copy" || extensions.release_status === "not_release_eligible";
}

export function trustedWorkingCopyBanner(overallStatus: unknown): string {
  const status = typeof overallStatus === "string" ? overallStatus.replace(/[^A-Za-z0-9_-]/gu, "") : "unknown";
  return `<aside role="alert" data-release-status="not-release-eligible"><strong>NOT RELEASE-ELIGIBLE — WORKING COPY</strong><p>Validation status: ${status || "unknown"}. This artifact preserves every validation check status, including failed and not_run when present, and must not be used as a release bundle.</p></aside>`;
}

/** Apply the one package-owned deterministic transformation allowed after rendering. */
export async function applyTrustedWorkingCopyMarking(
  outputDirectory: string,
  overallStatus: unknown,
): Promise<void> {
  const banner = trustedWorkingCopyBanner(overallStatus);
  for (const memberPath of TRUSTED_HTML_OUTPUT_PATHS) {
    const absolutePath = path.join(outputDirectory, ...memberPath.split("/"));
    const info = await lstat(absolutePath);
    if (!info.isFile() || info.isSymbolicLink()) {
      throw new Error(`Trusted renderer HTML output is not a regular file: ${memberPath}`);
    }
    const html = await readFile(absolutePath, "utf8");
    if (html.includes('data-release-status="not-release-eligible"')) continue;
    const bodyMatch = /<body\b[^>]*>/iu.exec(html);
    const marked = bodyMatch === null
      ? `${banner}\n${html}`
      : `${html.slice(0, bodyMatch.index + bodyMatch[0].length)}\n${banner}${html.slice(bodyMatch.index + bodyMatch[0].length)}`;
    await writeFile(absolutePath, marked, { encoding: "utf8", mode: 0o644 });
  }
}

export async function rewriteTrustedRendererOutputs(
  outputDirectory: string,
  report: unknown,
  attestation: unknown,
  generationAudit: unknown,
  workingCopy: boolean,
): Promise<string[]> {
  const rendered = await renderReport(report, {
    outDir: outputDirectory,
    attestation,
    ...(generationAudit === null ? {} : { generationAudit }),
    force: true,
  });
  if (workingCopy) {
    const status = typeof attestation === "object" && attestation !== null && !Array.isArray(attestation)
      ? (attestation as Record<string, unknown>).overall_status
      : undefined;
    await applyTrustedWorkingCopyMarking(outputDirectory, status);
  }
  return rendered.writtenFiles;
}

/**
 * Re-render with the package-owned renderer/template set and compare every
 * generated byte. This deliberately trusts neither supplied HTML nor a stale
 * manifest assertion about the renderer.
 */
export async function inspectTrustedRendererProjection(
  bundleRoot: string,
  report: unknown,
  attestation: unknown,
  generationAudit: unknown,
  workingCopy: boolean,
  members: readonly PackageFile[],
): Promise<TrustedRenderIssue[]> {
  const temporaryRoot = await mkdtemp(path.join(tmpdir(), "report-prompt-trusted-render-"));
  try {
    const expectedPaths = await rewriteTrustedRendererOutputs(
      temporaryRoot,
      report,
      attestation,
      generationAudit,
      workingCopy,
    );
    const expectedSet = new Set(expectedPaths);
    const issues: TrustedRenderIssue[] = [];

    for (const memberPath of [...expectedSet].sort()) {
      const expectedPath = path.join(temporaryRoot, ...memberPath.split("/"));
      const actualPath = path.join(bundleRoot, ...memberPath.split("/"));
      let actualInfo;
      try {
        actualInfo = await lstat(actualPath);
      } catch (error) {
        if (typeof error === "object" && error !== null && "code" in error && error.code === "ENOENT") {
          issues.push({
            code: "TRUSTED_RENDER_OUTPUT_MISSING",
            path: memberPath,
            message: `Package-owned renderer output is missing: ${memberPath}.`,
          });
          continue;
        }
        throw error;
      }
      if (!actualInfo.isFile() || actualInfo.isSymbolicLink()) {
        issues.push({
          code: "TRUSTED_RENDER_OUTPUT_MISSING",
          path: memberPath,
          message: `Package-owned renderer output is not a regular file: ${memberPath}.`,
        });
        continue;
      }
      const [expected, actual] = await Promise.all([sha256File(expectedPath), sha256File(actualPath)]);
      if (expected.contentHash !== actual.contentHash || expected.byteSize !== actual.byteSize) {
        issues.push({
          code: "TRUSTED_RENDER_OUTPUT_MISMATCH",
          path: memberPath,
          message: `${memberPath} is not the deterministic package-owned projection of scientific-report.public.json.`,
          expectedHash: expected.contentHash,
          actualHash: actual.contentHash,
        });
      }
    }

    const presentationRoles = new Set(["report_html", "annex_html", "style", "script", "icon"]);
    for (const member of members) {
      if (!presentationRoles.has(member.role)) continue;
      if (!expectedSet.has(member.path)) {
        issues.push({
          code: "UNTRUSTED_GENERATED_OUTPUT",
          path: member.path,
          message: `Presentation member ${member.path} is outside the package-owned renderer output set.`,
        });
      }
    }
    return issues;
  } finally {
    await rm(temporaryRoot, { recursive: true, force: true });
  }
}
